### Fetch all tasks

GET http://localhost:3200/tasks
Content-Type: application/json

### Create a new task
POST http://localhost:3200/tasks
Content-Type: application/json

{
    "title": "Testing",
    "date": "2022-01-01T12:00:00Z",
    "description": "lorem testing in 2022",
    "priority": "normal",
    "status": "todo"
}

### Update A Task
PUT http://localhost:3200/tasks
Content-Type: application/json

{
    "id": "90ccb743-8e44-4f8e-8785-21d6d1f667ea",
    "status": "inProgress"
}